### ISSUE TITLE
Unable to install with NodeJS 13

### ISSUE THREAD

**Issue by bomb-on** [MoneroOcean/node-cryptoforknote-util#10]
I tried to install this with NodeJS 13 on Ubuntu 18 but it looks like it's failing on build step, complete log as follows:

```$ npm install https://github.com/MoneroOcean/node-cryptoforknote-util.git

> cryptoforknote-util@7.0.2 install /home/pool/test/node_modules/cryptoforknote-util
> node-gyp rebuild

make: Entering directory '/home/pool/test/node_modules/cryptoforknote-util/build'
  CXX(target) Release/obj.target/cryptoforknote/src/main.o
../src/main.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE construct_block_blob(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/main.cc:225:69: error: no matching function for call to ‘v8::Array::Get(int&)’
         for (int i = 0; i < 32; i++ ) b.cycle.data[i] = cycle->Get(i)->NumberValue(isolate->GetCurrentContext()).ToChecked();
                                                                     ^
In file included from /home/pool/.cache/node-gyp/13.13.0/include/node/node.h:67:0,
                 from ../src/main.cc:2:
/home/pool/.cache/node-gyp/13.13.0/include/node/v8.h:3594:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/pool/.cache/node-gyp/13.13.0/include/node/v8.h:3594:43: note:   candidate expects 2 arguments, 1 provided
/home/pool/.cache/node-gyp/13.13.0/include/node/v8.h:3597:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/pool/.cache/node-gyp/13.13.0/include/node/v8.h:3597:43: note:   candidate expects 2 arguments, 1 provided
cryptoforknote.target.mk:127: recipe for target 'Release/obj.target/cryptoforknote/src/main.o' failed
make: *** [Release/obj.target/cryptoforknote/src/main.o] Error 1
make: Leaving directory '/home/pool/test/node_modules/cryptoforknote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pool/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-96-generic
gyp ERR! command "/home/pool/.nvm/versions/node/v13.13.0/bin/node" "/home/pool/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pool/test/node_modules/cryptoforknote-util
gyp ERR! node -v v13.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptoforknote-util@7.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptoforknote-util@7.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pool/.npm/_logs/2020-04-24T13_11_48_845Z-debug.log
```

and also:

```$ cat /home/pool/.npm/_logs/2020-04-24T13_11_48_845Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/pool/.nvm/versions/node/v13.13.0/bin/node',
1 verbose cli   '/home/pool/.nvm/versions/node/v13.13.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'https://github.com/MoneroOcean/node-cryptoforknote-util.git'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.13.0
4 verbose npm-session 206f8f8976b8a88c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 info lifecycle cryptoforknote-util@7.0.2~prepack: cryptoforknote-util@7.0.2
8 info lifecycle cryptoforknote-util@7.0.2~postpack: cryptoforknote-util@7.0.2
9 silly pacote git manifest for undefined@git+https://github.com/MoneroOcean/node-cryptoforknote-util.git fetched in 2263ms
10 timing stage:loadCurrentTree Completed in 2310ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule cryptoforknote-util@7.0.2 checking installable status
18 http fetch GET 200 https://registry.npmjs.org/bindings 206ms
19 http fetch GET 200 https://registry.npmjs.org/nan 205ms
20 http fetch GET 200 https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz 100ms
21 http fetch GET 200 https://registry.npmjs.org/nan/-/nan-2.14.1.tgz 106ms
22 silly pacote range manifest for bindings@* fetched in 334ms
23 silly resolveWithNewModule bindings@1.5.0 checking installable status
24 silly pacote range manifest for nan@^2.0.0 fetched in 326ms
25 silly resolveWithNewModule nan@2.14.1 checking installable status
26 http fetch GET 200 https://registry.npmjs.org/file-uri-to-path 53ms
27 http fetch GET 200 https://registry.npmjs.org/file-uri-to-path/-/file-uri-to-path-1.0.0.tgz 56ms
28 silly pacote version manifest for file-uri-to-path@1.0.0 fetched in 115ms
29 silly resolveWithNewModule file-uri-to-path@1.0.0 checking installable status
30 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 462ms
31 timing stage:loadIdealTree Completed in 467ms
32 silly currentTree test@1.0.0
33 silly idealTree test@1.0.0
33 silly idealTree ├── bindings@1.5.0
33 silly idealTree ├── cryptoforknote-util@7.0.2
33 silly idealTree ├── file-uri-to-path@1.0.0
33 silly idealTree └── nan@2.14.1
34 silly install generateActionsToTake
35 timing stage:generateActionsToTake Completed in 5ms
36 silly diffTrees action count 4
37 silly diffTrees add file-uri-to-path@1.0.0
38 silly diffTrees add bindings@1.5.0
39 silly diffTrees add nan@2.14.1
40 silly diffTrees add cryptoforknote-util@7.0.2
41 silly decomposeActions action count 32
42 silly decomposeActions fetch file-uri-to-path@1.0.0
43 silly decomposeActions extract file-uri-to-path@1.0.0
44 silly decomposeActions preinstall file-uri-to-path@1.0.0
45 silly decomposeActions build file-uri-to-path@1.0.0
46 silly decomposeActions install file-uri-to-path@1.0.0
47 silly decomposeActions postinstall file-uri-to-path@1.0.0
48 silly decomposeActions finalize file-uri-to-path@1.0.0
49 silly decomposeActions refresh-package-json file-uri-to-path@1.0.0
50 silly decomposeActions fetch bindings@1.5.0
51 silly decomposeActions extract bindings@1.5.0
52 silly decomposeActions preinstall bindings@1.5.0
53 silly decomposeActions build bindings@1.5.0
54 silly decomposeActions install bindings@1.5.0
55 silly decomposeActions postinstall bindings@1.5.0
56 silly decomposeActions finalize bindings@1.5.0
57 silly decomposeActions refresh-package-json bindings@1.5.0
58 silly decomposeActions fetch nan@2.14.1
59 silly decomposeActions extract nan@2.14.1
60 silly decomposeActions preinstall nan@2.14.1
61 silly decomposeActions build nan@2.14.1
62 silly decomposeActions install nan@2.14.1
63 silly decomposeActions postinstall nan@2.14.1
64 silly decomposeActions finalize nan@2.14.1
65 silly decomposeActions refresh-package-json nan@2.14.1
66 silly decomposeActions fetch cryptoforknote-util@7.0.2
67 silly decomposeActions extract cryptoforknote-util@7.0.2
68 silly decomposeActions preinstall cryptoforknote-util@7.0.2
69 silly decomposeActions build cryptoforknote-util@7.0.2
70 silly decomposeActions install cryptoforknote-util@7.0.2
71 silly decomposeActions postinstall cryptoforknote-util@7.0.2
72 silly decomposeActions finalize cryptoforknote-util@7.0.2
73 silly decomposeActions refresh-package-json cryptoforknote-util@7.0.2
74 silly install executeActions
75 silly doSerial global-install 32
76 verbose correctMkdir /home/pool/.npm/_locks correctMkdir not in flight; initializing
77 verbose lock using /home/pool/.npm/_locks/staging-95837436bdbb9418.lock for /home/pool/test/node_modules/.staging
78 silly doParallel extract 4
79 silly extract file-uri-to-path@1.0.0
80 silly extract bindings@1.5.0
81 silly extract nan@2.14.1
82 silly extract cryptoforknote-util@7.0.2
83 silly tarball trying file-uri-to-path@1.0.0 by hash: sha512-0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==
84 silly tarball trying bindings@* by hash: sha512-p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==
85 silly tarball trying nan@^2.0.0 by hash: sha512-isWHgVjnFjh2x2yuJ/tj3JbwoHu3UC2dX5G/88Cm24yB6YopVgxvBObDY7n5xW6ExmFhJpSEQqFPvq9zaXc8Jw==
86 silly tarball no local data for git+https://github.com/MoneroOcean/node-cryptoforknote-util.git. Extracting by manifest.
87 silly extract bindings@* extracted to /home/pool/test/node_modules/.staging/bindings-53bcacc4 (77ms)
88 silly extract file-uri-to-path@1.0.0 extracted to /home/pool/test/node_modules/.staging/file-uri-to-path-3cf46cd9 (81ms)
89 silly extract nan@^2.0.0 extracted to /home/pool/test/node_modules/.staging/nan-bb63e09a (89ms)
90 timing audit submit Completed in 283ms
91 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 283ms
92 timing audit body Completed in 1ms
93 info lifecycle cryptoforknote-util@7.0.2~prepack: cryptoforknote-util@7.0.2
94 info lifecycle cryptoforknote-util@7.0.2~postpack: cryptoforknote-util@7.0.2
95 silly extract git+https://github.com/MoneroOcean/node-cryptoforknote-util.git extracted to /home/pool/test/node_modules/.staging/cryptoforknote-util-b429f1e8 (1672ms)
96 timing action:extract Completed in 1683ms
97 silly doReverseSerial unbuild 32
98 silly doSerial remove 32
99 silly doSerial move 32
100 silly doSerial finalize 32
101 silly finalize /home/pool/test/node_modules/file-uri-to-path
102 silly finalize /home/pool/test/node_modules/bindings
103 silly finalize /home/pool/test/node_modules/nan
104 silly finalize /home/pool/test/node_modules/cryptoforknote-util
105 timing action:finalize Completed in 12ms
106 silly doParallel refresh-package-json 4
107 silly refresh-package-json /home/pool/test/node_modules/file-uri-to-path
108 silly refresh-package-json /home/pool/test/node_modules/bindings
109 silly refresh-package-json /home/pool/test/node_modules/nan
110 silly refresh-package-json /home/pool/test/node_modules/cryptoforknote-util
111 timing action:refresh-package-json Completed in 17ms
112 silly doParallel preinstall 4
113 silly preinstall file-uri-to-path@1.0.0
114 info lifecycle file-uri-to-path@1.0.0~preinstall: file-uri-to-path@1.0.0
115 silly preinstall bindings@1.5.0
116 info lifecycle bindings@1.5.0~preinstall: bindings@1.5.0
117 silly preinstall nan@2.14.1
118 info lifecycle nan@2.14.1~preinstall: nan@2.14.1
119 silly preinstall cryptoforknote-util@7.0.2
120 info lifecycle cryptoforknote-util@7.0.2~preinstall: cryptoforknote-util@7.0.2
121 timing action:preinstall Completed in 0ms
122 silly doSerial build 32
123 silly build file-uri-to-path@1.0.0
124 info linkStuff file-uri-to-path@1.0.0
125 silly linkStuff file-uri-to-path@1.0.0 has /home/pool/test/node_modules as its parent node_modules
126 silly build bindings@1.5.0
127 info linkStuff bindings@1.5.0
128 silly linkStuff bindings@1.5.0 has /home/pool/test/node_modules as its parent node_modules
129 silly build nan@2.14.1
130 info linkStuff nan@2.14.1
131 silly linkStuff nan@2.14.1 has /home/pool/test/node_modules as its parent node_modules
132 silly build cryptoforknote-util@7.0.2
133 info linkStuff cryptoforknote-util@7.0.2
134 silly linkStuff cryptoforknote-util@7.0.2 has /home/pool/test/node_modules as its parent node_modules
135 timing action:build Completed in 2ms
136 silly doSerial global-link 32
137 silly doParallel update-linked 0
138 silly doSerial install 32
139 silly install file-uri-to-path@1.0.0
140 info lifecycle file-uri-to-path@1.0.0~install: file-uri-to-path@1.0.0
141 silly install bindings@1.5.0
142 info lifecycle bindings@1.5.0~install: bindings@1.5.0
143 silly install nan@2.14.1
144 info lifecycle nan@2.14.1~install: nan@2.14.1
145 silly install cryptoforknote-util@7.0.2
146 info lifecycle cryptoforknote-util@7.0.2~install: cryptoforknote-util@7.0.2
147 verbose lifecycle cryptoforknote-util@7.0.2~install: unsafe-perm in lifecycle true
148 verbose lifecycle cryptoforknote-util@7.0.2~install: PATH: /home/pool/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pool/test/node_modules/cryptoforknote-util/node_modules/.bin:/home/pool/test/node_modules/.bin:/home/pool/.nvm/versions/node/v13.13.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
149 verbose lifecycle cryptoforknote-util@7.0.2~install: CWD: /home/pool/test/node_modules/cryptoforknote-util
150 silly lifecycle cryptoforknote-util@7.0.2~install: Args: [ '-c', 'node-gyp rebuild' ]
151 silly lifecycle cryptoforknote-util@7.0.2~install: Returned: code: 1  signal: null
152 info lifecycle cryptoforknote-util@7.0.2~install: Failed to exec install script
153 timing action:install Completed in 7404ms
154 verbose unlock done using /home/pool/.npm/_locks/staging-95837436bdbb9418.lock for /home/pool/test/node_modules/.staging
155 timing stage:rollbackFailedOptional Completed in 24ms
156 timing stage:runTopLevelLifecycles Completed in 11969ms
157 silly saveTree test@1.0.0
157 silly saveTree └─┬ cryptoforknote-util@7.0.2
157 silly saveTree   ├─┬ bindings@1.5.0
157 silly saveTree   │ └── file-uri-to-path@1.0.0
157 silly saveTree   └── nan@2.14.1
158 warn test@1.0.0 No description
159 warn test@1.0.0 No repository field.
160 verbose stack Error: cryptoforknote-util@7.0.2 install: `node-gyp rebuild`
160 verbose stack Exit status 1
160 verbose stack     at EventEmitter.<anonymous> (/home/pool/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
160 verbose stack     at EventEmitter.emit (events.js:315:20)
160 verbose stack     at ChildProcess.<anonymous> (/home/pool/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
160 verbose stack     at ChildProcess.emit (events.js:315:20)
160 verbose stack     at maybeClose (internal/child_process.js:1026:16)
160 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
161 verbose pkgid cryptoforknote-util@7.0.2
162 verbose cwd /home/pool/test
163 verbose Linux 4.15.0-96-generic
164 verbose argv "/home/pool/.nvm/versions/node/v13.13.0/bin/node" "/home/pool/.nvm/versions/node/v13.13.0/bin/npm" "install" "https://github.com/MoneroOcean/node-cryptoforknote-util.git"
165 verbose node v13.13.0
166 verbose npm  v6.14.4
167 error code ELIFECYCLE
168 error errno 1
169 error cryptoforknote-util@7.0.2 install: `node-gyp rebuild`
169 error Exit status 1
170 error Failed at the cryptoforknote-util@7.0.2 install script.
170 error This is probably not a problem with npm. There is likely additional logging output above.
171 verbose exit [ 1, true ]
```

Due to my limited knowledge with C/C++, I wonder if anyone could help out with solving this issue?
Thanks in advance!

**Comment by MoneroOcean** [comment]
Should be fixed https://github.com/MoneroOcean/node-cryptoforknote-util/commit/b47f6475acdca423f0532ee5a1b7e2ec25a51e32 ?

**Comment by bomb-on** [comment]
Uh, not sure why I missed your super quick response :/ Just confirming that this works now, thanks a ton for such a ultra fast help!
