### ISSUE TITLE
Installing Issue

### ISSUE THREAD

**Issue by element0355** [MoneroOcean/node-cryptoforknote-util#14]
When installing I receive the error below:

83 verbose stack Error: cryptoforknote-util@8.1.1 install: `node-gyp rebuild`
83 verbose stack Exit status 1
83 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
83 verbose stack     at EventEmitter.emit (events.js:315:20)
83 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
83 verbose stack     at ChildProcess.emit (events.js:315:20)
83 verbose stack     at maybeClose (internal/child_process.js:1021:16)
83 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
84 verbose pkgid cryptoforknote-util@8.1.1
85 verbose cwd /home/pool/pool/node_modules
86 verbose Linux 4.15.0-66-generic
87 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/MoneroOcean/node-cryptoforknote-util"
88 verbose node v12.18.2
89 verbose npm  v6.14.6
90 error code ELIFECYCLE
91 error errno 1
92 error cryptoforknote-util@8.1.1 install: `node-gyp rebuild`
92 error Exit status 1
93 error Failed at the cryptoforknote-util@8.1.1 install script.
93 error This is probably not a problem with npm. There is likely additional logging output above.
94 verbose exit [ 1, true ]

Can anyone help on this?

Ubuntu 18.04

**Comment by element0355** [comment]
Used the pending pull request by @sanich-rd  and the issue went away.
